apiVersion: kubevent.innobead/v1alpha1
kind: EventBroker
metadata:
  name: kafka
spec:
  activate: true
  kafka:
    addresses:
      - 172.17.0.3:30092
    topic: kubevent
  watch_all_resources: false
  watch_resources:
    - group: ""
      version: v1
      kind: Pod
    - group: ""
      version: v1
      kind: Service
    - group: apps
      version: v1
      kind: DaemonSet