apiVersion: kubevent.innobead/v1alpha1
kind: EventBroker
metadata:
  name: kafka
spec:
  activate: true
  kafka:
    addresses:
      - localhost:9092
    topic: kubevent
  resources:
    - group: ""
      version: v1
      kind: Pod
    - group: ""
      version: v1
      kind: Service
    - group: apps
      version: v1
      kind: DaemonSet