log:
  level: info

offset:
  time: "" #  "" means now or RFC3339 format = "2006-01-02T15:04:05Z"

resources:
  - kind: pod
  - kind: replicationcontroller
  - kind: service
  - kind: namespace
  - kind: persistentvolume
  - kind: persistentvolumeclaim
  - kind: secret
  - kind: configmap
  - kind: endpoints
  - kind: daemonset
  - kind: statefulset
  - kind: replicaset
  - kind: deployment
  - kind: job
  - kind: cronjob
  - kind: ingress
  - kind: storageclass

brokers:
  - type: amqp
    value:
      uri: "amqp://rabbitmq:rabbitmq@localhost:5672/"
      exchange: kubevent
